
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - 'c:\Users\Felipe\Documents\my-lab\dev-task-manager-BE\temp\PROD\OSFDigital\CO-TRICOT-IFB-Tricot-SFCC\TRI-61\release\v7.0.0__feature\STRI-208\2023-5-12__2-41\metadata\v7_0_0\meta\system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface Category {
			/**
			* CTA Button Custom Label

				
                    You can set a custom label for the CTA button displayed below the sub-categories carousel. 
                    
                    If nothing was provided, it will use the prefix label set on Page Designer component. And will result in: ctaButtonPrefixLabel + CATEGORY LABEL (Category label is the same as the top navigation tabs of the carousel)
                    
                    Or if any of them was provided, it will use the code default (Ver Todo)
                
			* @group customAttributes - Custom
			* @source [attribute](file:c:\Users\Felipe\Documents\my-lab\dev-task-manager-BE\temp\PROD\OSFDigital\CO-TRICOT-IFB-Tricot-SFCC\TRI-61\release\v7.0.0__feature\STRI-208\2023-5-12__2-41\metadata\v7_0_0\meta\system-objecttype-extensions.xml#5) | [group](file:c:\Users\Felipe\Documents\my-lab\dev-task-manager-BE\temp\PROD\OSFDigital\CO-TRICOT-IFB-Tricot-SFCC\TRI-61\release\v7.0.0__feature\STRI-208\2023-5-12__2-41\metadata\v7_0_0\meta\system-objecttype-extensions.xml#41)
			*/
			ctaButtonCustomLabel: string | null;

			/**
			* CTA Button Custom URL

				You can use a custom URL for this CTA button, provide the URL on this field. If nothing was provided it will use the normal category URL.
			* @group customAttributes - Custom
			* @source [attribute](file:c:\Users\Felipe\Documents\my-lab\dev-task-manager-BE\temp\PROD\OSFDigital\CO-TRICOT-IFB-Tricot-SFCC\TRI-61\release\v7.0.0__feature\STRI-208\2023-5-12__2-41\metadata\v7_0_0\meta\system-objecttype-extensions.xml#20) | [group](file:c:\Users\Felipe\Documents\my-lab\dev-task-manager-BE\temp\PROD\OSFDigital\CO-TRICOT-IFB-Tricot-SFCC\TRI-61\release\v7.0.0__feature\STRI-208\2023-5-12__2-41\metadata\v7_0_0\meta\system-objecttype-extensions.xml#42)
			*/
			ctaButtonCustomURL: string | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
		
	}
}